### ISSUE TITLE
sub menus don't work 

### ISSUE THREAD

**Issue by melbournevijay** [ireade/accessible-dropdown-navigation#1]
Awesome script... thanks for sharing.
However, on a mac, in both chrome and firefox, clicking on sub-menu or sub-sub-menu items has not effect

http://raju.com.au/demo/accessible-dropdown-navigation/

Clicking on the menu item VJ deisgn in top level of the menu, takes you to the website. Clicking on sub-menu links does not work.

**Comment by ireade** [comment]
Hi @melbournevijay , you're welcome :)

Thanks for bringing this to my attention. I have fixed this in my latest commit. Please reopen if it doesn't work for you.

**Comment by melbournevijay** [comment]
Hi Ire,

Does not work on mobile anymore?...

Cheers, 

VJ

Vijay Rudraraju

Mobile +61 405 731 282

Gmail/Skype/Twitter @ melbournevijay

http://vjdesign.com.au

On Thu, Nov 26, 2015 at 11:04 AM -0800, "Ire Aderinokun" notifications@github.com wrote:

Hi @melbournevijay , you're welcome :)

Thanks for bringing this to my attention. I have fixed this in my latest commit. Please reopen if it doesn't work for you.
